---
- name: "create backup of current kubeconfig file"
  ansible.builtin.copy:
    src: "{{ openshift_kubeconfig_file }}"
    dest: "{{ openshift_kubeconfig_file }}.bkp"
    remote_src: true
    mode: "600"

- name: "extract current CA from openshift cluster"
  environment:
    KUBECONFIG: "{{ openshift_kubeconfig_file }}"
    CERTPATH: "{{ kubeconfigca_cert_path }}"
  ansible.builtin.shell:
    cmd: |
      POD=$(oc --insecure-skip-tls-verify get pods -n openshift-authentication --no-headers | cut -d " " -f1 | head -n 1)
      oc --insecure-skip-tls-verify -n openshift-authentication rsh "${POD}" cat /run/secrets/kubernetes.io/serviceaccount/ca.crt > "${CERTPATH}"/ingress-ca.crt
  changed_when: true

- name: Slurp ingress-ca.crt
  ansible.builtin.slurp:
    src: "{{ kubeconfigca_cert_path }}/ingress-ca.crt"
  register: kubeconfigca_cert

- name: Slurp current kubeconfig
  ansible.builtin.slurp:
    src: "{{ openshift_kubeconfig_file }}"
  register: kubeconfigca_config

- name: Read kubeconfig to dictionary
  ansible.builtin.set_fact:
    kubeconfigca_content: "{{ kubeconfigca_config['content'] | b64decode | from_yaml }}"

- name: Patch kubeconfig dictionary
  ansible.builtin.set_fact:
    kubeconfigca_data: "{{ kubeconfigca_content | combine(changeddata, recursive=True) }}"
  vars:
    changeddata:
      clusters:
        - cluster:
            server: "{{ kubeconfigca_content['clusters'][0]['cluster']['server'] }}"
            certificate-authority-data: "{{ kubeconfigca_cert['content'] }}"
          name: "{{ kubeconfigca_content['clusters'][0]['name'] }}"


- name: "Write changed kubeconfig file"
  ansible.builtin.copy:
    content: "{{ kubeconfigca_data | to_nice_yaml }}"
    dest: "{{ openshift_kubeconfig_file }}"
    backup: true
    mode: "0600"
    owner: "{{ kubeconfigca_user }}"

- name: "Copy kubeconfig to userlocation"
  ansible.builtin.copy:
    content: "{{ kubeconfigca_data | to_nice_yaml }}"
    dest: "{{ kubeconfigca_user_kubeconfig }}"
    backup: true
    mode: "0600"
    owner: "{{ kubeconfigca_user }}"

- name: "delete ingress-ca.crt"
  ansible.builtin.file:
    state: absent
    path: "{{ kubeconfigca_cert_path }}/ingress-ca.crt"
...
